### ISSUE TITLE
Lack of accessible name for frames.

### ISSUE THREAD

**Issue by AEDesigns** [h5p/h5p-blanks#113]
For each <frame> or <iframe> element, provide an accessible name using ONE of the following methods.  Good title attribute  Better aria-label attribute  Best aria-labelledby attribute
![fill_in_the_blank](https://user-images.githubusercontent.com/43253284/166331349-d7465ec6-b32e-47a7-ab11-e16d8eb1b79e.PNG)

**Comment by fnoks** [comment]
H5P already supports setting an accessibility name for the iframe. In what context are you using H5P? (h5p.com or any of the plugins). Either way, this issue is put in the wrong repository, since this is not solved by Fill in the blanks, but the core of H5P.
