### ISSUE TITLE
Focus shifts from navigation bar under Module 1 <h1> header to bypass button located in main content.

### ISSUE THREAD

**Issue by AEDesigns** [h5p/h5p-blanks#114]
When users navigate through a web page, they expect to encounter controls and other content in an order that makes sense and makes it easy to use the page's functionality. Poor focus order can be disorienting to people who use screen readers or screen magnifiers and to people with reading disorders. Poor focus order can also make it difficult or even painful for people who use keyboards because of mobility impairments.
![image](https://user-images.githubusercontent.com/43253284/166332219-743410ad-4602-4de1-9d40-c0c50edfc5f6.png)

**Comment by fnoks** [comment]
For me, it seems the comment is about Moodle. I am therefore closing this one. Please let me know if you disagree.
