### ISSUE TITLE
There are 2 main landmarks when there should only be 1.

### ISSUE THREAD

**Issue by AEDesigns** [h5p/h5p-blanks#115]
People with good vision can quickly scan a page to identify its primary content. Users of assistive technology expect all primary content to be contained within the page's main landmark. If primary content appears elsewhere, they might not be able to find it.

![2ml](https://user-images.githubusercontent.com/43253284/166461014-8f86e878-941e-43b3-9c22-8770fe099a00.PNG)

**Comment by fnoks** [comment]
For me, it seems the comment is about the platform you are using, and not the H5P itself. I am therefore closing this one. Please let me know if you disagree.
