### ISSUE TITLE
Instructions text is coded as a header, but does not function as a header.

### ISSUE THREAD

**Issue by AEDesigns** [h5p/h5p-blanks#116]
The function of a heading is to label a section of content. Assistive technologies allow users to quickly navigate through the coded headings on the page to find content of interest. Users are likely to be confused if they unexpectedly navigate to text that doesn't function as a heading.
![heading](https://user-images.githubusercontent.com/43253284/166464612-386c511a-1a47-4483-be25-7a46e2473b89.PNG)

**Comment by AEDesigns** [comment]
Ill double check for sure!

**Comment by fnoks** [comment]
It doesn't seem H5P can fix this. Therefore closing it.
