### ISSUE TITLE
Fill in the blanks activity memory leak, activity uses 2 GB of memory in moodle but works fine on wordpress

### ISSUE THREAD

**Issue by mgancarzdsi** [h5p/h5p-blanks#33]
Quoting @thomasmars: "Hi, this is an issue with the implementation of Fill in the Blanks' getXAPIData() function/contract and the xAPI specification. When there are many alternatives for each blank generating the xAPI statement becomes exponentially big. This manifests in Moodle since it is the only platform that calls the getXAPIData() contract to generate reports. Please move this issue to the Blanks repository, as that is the library that has to change its' implementation of getXAPIData() in order to not crash. Thanks."

_Originally posted by @thomasmars in https://github.com/h5p/h5p-moodle-plugin/issues/259#issuecomment-472761108_

**Comment by mgancarzdsi** [comment]
Moved from https://github.com/h5p/h5p-moodle-plugin/issues/259 to here, see above for details and below for my user experience.

This activity: https://h5p.org/node/456374 seems to work fine on h5p.org and our own Wordpress site. However, when we import the .h5p file it into our Moodle, clicking "Check" causes Google Chrome to start using memory until it reaches about 2 GB, at which point the tab crashes. In Internet Explorer it takes a while but works, though it uses up roughly 1.7 GB of memory while the activity grading is taking place.

Deleting one of the questions does reduce the memory usage and allows the "Check" to complete without Google Chrome crashing.

We created the activity in our Moodle, on Moodle version 3.5.3 and H5P plugin version 1.14. I also updated our H5P plugin to latest 1.17.1 and the same behaviour still happens.

**Comment by TubsDK** [comment]
We can verify the same bug which our costumer has reported https://h5p.org/node/530103#comment-form

**Comment by thomasmars** [comment]
Hi, the issue was solved in https://github.com/h5p/h5p-blanks/commit/f28e78d4736d8b7da306e19da0650521555cc92e and https://github.com/h5p/h5p-blanks/commit/f635e9b10bc3ac04d31ba9b21f16ccaffbf2c60e and is part of the latest version of h5p-blanks, please download it at H5P.com or by updating the content type through the content type hub(H5P editor) on your webpage.

**Comment by TubsDK** [comment]
Thanks for letting me know - but it seems the current content type version on h5p.org is 1.11 and the current version in the moodle plug is also 1.11 
![image](https://user-images.githubusercontent.com/8876269/59274481-b863bc00-8c5a-11e9-9d66-d0ef83005eba.png)

![image](https://user-images.githubusercontent.com/8876269/59274539-d03b4000-8c5a-11e9-86bc-1b7c5c133a53.png)

If i read your git repo correctly, your fix is added to release 1.12 https://github.com/h5p/h5p-blanks/blob/5916fc07e450ae54b963ba996791da4b5d80d72c/library.json#L6 . which has yet to be released?

**Comment by thomasmars** [comment]
Hmm, you have the correct version then, it should be fixed in version 1.11.4, so you should have the fix then. Are you able to link me the .h5p file in question ?

**Comment by TubsDK** [comment]
The h5p files is linked here https://h5p.org/sites/default/files/fill-in-the-blanks-skabelon-8027.h5p

**Comment by thomasmars** [comment]
Looking at the library.json of H5P.Blanks-1.11 in that package it says:
`  "title": "Fill in the Blanks",
  "description": "Test your users with fill in the blanks tasks(Cloze tests).",
  "machineName": "H5P.Blanks",
  "majorVersion": 1,
  "minorVersion": 11,
  "patchVersion": 3,`
So the content has either not been upgraded or Fill in the Blanks is not installed properly on your server. I suggest trying to upload H5P.Blanks again to your page, to see if that upgrades the content. I'll run a check to see if it works on my local Moodle site.

**Comment by thomasmars** [comment]
Seems to work fine in the latest Moodle plugin version. I uploaded the .h5p file as new content, then went into the content type hub and updated the "Fill in the Blanks" content type, when I revisit the content it is upgraded as expected.

**Comment by TubsDK** [comment]
Thanks for helping out - we uploaded the 1.11.4. content type manually to the moodle site and now it works beautifully.

**Comment by thomasmars** [comment]
Excellent :+1:
