### ISSUE TITLE
[Feature Request] Automatic checking of answers

### ISSUE THREAD

**Issue by timothyylim** [h5p/h5p-blanks#8]
To solve this issue, it can check the answer after the user has inputed a letter. For example:

N <---- Checks but not the right answer - No comfirmation given.

No <---- Checks but not the right answer - No comfirmation given.

Nor <---- Checks but not the right answer - No comfirmation given.

Norw <---- Checks but not the right answer - No comfirmation given.

Norwa <---- Checks but not the right answer - No comfirmation given.

Norway <---- Checks and finds the right answer.

The user would be able to keep trying until they get the right answer.

From the forum post: https://h5p.org/fill-in-the-blanks

**Comment by otacke** [comment]
This has already been implemented, right?

**Comment by timothyylim** [comment]
Yup. I've closed it as the current implementation fits what I was envisioning.
